FROM golang:1.18-alpine

WORKDIR /app

COPY ./ ./

RUN apk --no-cache add ca-certificates

RUN apk --no-cache add gcc g++ make
RUN apk add git
RUN apk add curl
RUN apk add nodejs npm

RUN go mod download

#CMD ["go", "run", "main.go"]

EXPOSE 9900